
'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Header/Header";
import ThemeProvider from "@/components/ui/theme-provider";
import { Provider } from "react-redux";
import { store } from "./store/store";
import { Toaster } from "sonner";
import  Footer  from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<Provider store={store}>
        <ThemeProvider
             attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
          
        <Header></Header>
        <Toaster richColors
        position="top-center"></Toaster>
        {children}

        <Footer></Footer>
        </ThemeProvider>


        </Provider>
      </body>
    </html>
  );
}


